language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.3
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
licenses:
    - 'android-sdk-license-.+'

before_script: cd game

before_install:
  - yes | sdkmanager "platforms;android-27"
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
